version: '3.8'

services:
  db:
    image: postgres:13
    environment:
      - POSTGRES_USER=meetcube_user
      - POSTGRES_PASSWORD=meetcube_pass
      - POSTGRES_DB=meetcube_db
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  web:
    build: .
    command: >
      sh -c "sleep 5 && 
        python manage.py makemigrations &&
        python manage.py migrate &&
        python manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      DB_NAME: meetcube_db
      DB_USER: meetcube_user
      DB_PASSWORD: meetcube_pass
      DB_HOST: db
      DB_PORT: 5432

volumes:
  pgdata:
