# Generated by Django 4.2.19 on 2025-02-10 20:46

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RoomBooking',
            fields=[
                ('room_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('booked_by', models.CharField(max_length=255)),
                ('booking_start', models.DateTimeField()),
                ('duration_minutes', models.PositiveIntegerField()),
            ],
        ),
    ]
